// Code generated by Wire. DO NOT EDIT (regenerated manually; run `wire ./cmd/sync` after changes).

//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"log/slog"

	"github.com/KridtinC/pocketbase/internal/adapter/outbound/mongorepo"
	"github.com/KridtinC/pocketbase/internal/adapter/outbound/pokeapi"
	"github.com/KridtinC/pocketbase/internal/core/port"
	"github.com/KridtinC/pocketbase/internal/core/service"
)

func initializeSync(ctx context.Context, cfg syncConfig, logger *slog.Logger) (*syncApp, func(), error) {
	mongoCfg := provideSyncMongoConfig(cfg)
	pokeCfg := provideSyncPokeAPIConfig(cfg)

	client, err := mongorepo.NewClient(ctx, mongoCfg)
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() {
		_ = client.Disconnect(context.Background())
	}

	db := mongorepo.NewDatabase(client, mongoCfg)
	pokemonRepo := mongorepo.NewPokemonRepo(db)
	moveRepo := mongorepo.NewMoveRepo(db)
	abilityRepo := mongorepo.NewAbilityRepo(db)
	typeRepo := mongorepo.NewTypeRepo(db)
	eggGroupRepo := mongorepo.NewEggGroupRepo(db)
	evolutionRepo := mongorepo.NewEvolutionRepo(db)
	itemRepo := mongorepo.NewItemRepo(db)
	natureRepo := mongorepo.NewNatureRepo(db)

	pokeClient := pokeapi.NewClient(pokeCfg)
	var pokeIface port.PokeAPIClient = pokeClient

	deps := provideSyncDeps(pokeIface, pokemonRepo, moveRepo, abilityRepo, typeRepo, eggGroupRepo, evolutionRepo, itemRepo, natureRepo, logger)
	syncSvc := service.NewSyncService(deps)

	return &syncApp{Svc: syncSvc}, cleanup, nil
}
