// Code generated by Wire. DO NOT EDIT (regenerated manually; run `wire ./cmd/api` after changes).

//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	httpadapter "github.com/KridtinC/pocketbase/internal/adapter/inbound/http"
	"github.com/KridtinC/pocketbase/internal/adapter/outbound/mongorepo"
	"github.com/KridtinC/pocketbase/internal/core/service"
)

func initializeAPI(ctx context.Context, cfg appConfig) (*apiApp, func(), error) {
	mongoCfg := provideMongoConfig(cfg)
	routerCfg := provideRouterConfig(cfg)
	authCfg := provideAuthConfig(cfg)

	client, err := mongorepo.NewClient(ctx, mongoCfg)
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() {
		_ = client.Disconnect(context.Background())
	}

	db := mongorepo.NewDatabase(client, mongoCfg)

	pokemonRepo := mongorepo.NewPokemonRepo(db)
	moveRepo := mongorepo.NewMoveRepo(db)
	abilityRepo := mongorepo.NewAbilityRepo(db)
	typeRepo := mongorepo.NewTypeRepo(db)
	eggGroupRepo := mongorepo.NewEggGroupRepo(db)
	evolutionRepo := mongorepo.NewEvolutionRepo(db)
	itemRepo := mongorepo.NewItemRepo(db)
	natureRepo := mongorepo.NewNatureRepo(db)
	teamRepo := mongorepo.NewTeamRepo(db)
	userRepo := mongorepo.NewUserRepo(db)
	sessionRepo := mongorepo.NewSessionRepo(db)

	pokemonSvc := service.NewPokemonService(pokemonRepo)
	moveSvc := service.NewMoveService(moveRepo)
	abilitySvc := service.NewAbilityService(abilityRepo)
	typeSvc := service.NewTypeService(typeRepo)
	eggGroupSvc := service.NewEggGroupService(eggGroupRepo)
	evolutionSvc := service.NewEvolutionService(evolutionRepo)
	itemSvc := service.NewItemService(itemRepo)
	natureSvc := service.NewNatureService(natureRepo)
	teamSvc := service.NewTeamService(teamRepo)
	authSvc := service.NewAuthService(userRepo, sessionRepo, authCfg)

	deps := httpadapter.Deps{
		Pokemon:   pokemonSvc,
		Moves:     moveSvc,
		Abilities: abilitySvc,
		Types:     typeSvc,
		EggGroups: eggGroupSvc,
		Evo:       evolutionSvc,
		Items:     itemSvc,
		Natures:   natureSvc,
		Teams:     teamSvc,
		Auth:      authSvc,
		Config:    routerCfg,
	}
	router := httpadapter.NewRouter(deps)

	return &apiApp{Router: router, DB: db}, cleanup, nil
}
